module Lex = Lex
module Gen = Gen
module Css_output = Css_output

let print chan css =
  Fmt.pf
    (Format.formatter_of_out_channel chan)
    "@[<v>/* Generated by sx, PLEASE DO NOT EDIT! */@,%s@,@,%a@]@."
    Preflight.css Css_output.pp css
